version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: djbase
      POSTGRES_PASSWORD: password
      POSTGRES_DB: the_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "18000:8000"
    command: ./docker-entrypoint.sh
    working_dir: /usr/src/app
    environment:
      DATABASE_HOST: db
      DJANGO_SETTINGS_MODULE: main.local_settings
      DATABASE_USER: djbase
      DATABASE_PASSWORD: password
      DATABASE_NAME: the_db
    depends_on:
      - "db"
    volumes:
      - ".:/usr/src/app"

  test:
    build: .
    command: ./docker-entrypoint-test.sh
    environment:
      DATABASE_HOST: db
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
